// ===================================
// 프로젝트 데이터
// ===================================

export const projectsData = [
  {
    id: "riman",
    title: "리만코리아",
    category: "반응형 WEB",
    thumbnail: "./images/portfoilo_riman.png",
    tags: ["Vue3", "Quasar", "GSAP", "SCSS"],
    description: "리만코리아 사이트 퍼블리싱",
    client: "리만코리아",
    period: "2025.01 ~ 2025.03",
    role: "웹 퍼블리싱",
    contribution: "퍼블리싱 100%",
    url: "https://kr.riman.com/",
    images: ["./images/portfoilo_riman.png"],
    overview:
      "리만코리아 공식 웹사이트 리뉴얼 프로젝트입니다. Vue3 Quasar 프레임워크를 활용하여 반응형 웹사이트를 구축했습니다.",
    features: [
      "Vue3 Composition API 활용한 컴포넌트 기반 개발",
      "Quasar 프레임워크를 통한 빠른 UI 구현",
      "GSAP를 활용한 인터랙티브 애니메이션",
      "SCSS 모듈화를 통한 유지보수성 향상",
      "반응형(Mobile/Tablet/Desktop)",
    ],
  },
  {
    id: "qbid",
    title: "Q-bid",
    category: "적응형 WEB",
    thumbnail: "./images/portfolio_qbid.png",
    tags: ["Vue2", "SCSS"],
    description: "Q-bid 웹사이트 퍼블리싱",
    client: "나이스홀딩스",
    period: "2024.09 ~ 2024.12",
    role: "웹 퍼블리싱",
    contribution: "퍼블리싱 100%",
    url: "http://54.180.166.59:28080/",
    images: ["./images/portfolio_qbid.png"],
    overview: "Q-bid 플랫폼의 웹사이트 퍼블리싱 작업을 진행했습니다.",
    features: [
      "Vue2 기반 프로젝트 퍼블리싱",
      "SCSS를 활용한 스타일 관리",
      "적응형 웹 디자인 구현",
      "크로스 브라우징 대응",
    ],
  },
  {
    id: "ewha-medical",
    title: "이화의료원",
    category: "APP",
    thumbnail: "./images/portfoilo_medical_center.png",
    tags: ["ReactNative", "CSS", "JavaScript"],
    description: "이화의료원 APP 퍼블리싱",
    client: "이화의료원",
    period: "2023.06 ~ 2023.09",
    role: "앱 퍼블리싱",
    contribution: "퍼블리싱 50%",
    url: "#",
    images: ["./images/portfoilo_medical_center.png"],
    overview:
      "이화의료원 모바일 앱 퍼블리싱 프로젝트입니다. React Native를 활용하여 크로스 플랫폼 앱을 퍼블리싱 작업을 진행했습니다.",
    features: [
      "React Native 컴포넌트 퍼블리싱",
      "iOS/Android 크로스 플랫폼 대응",
      "네이티브 UI/UX 구현",
    ],
  },
  {
    id: "dari",
    title: "DARI",
    category: "WEB",
    thumbnail: "./images/portfoilo_dari.png",
    tags: ["HTML", "CSS", "JavaScript"],
    description: "마케팅 통합 툴 DARI 퍼블리싱",
    client: "DARI",
    period: "2022.06 ~ 2022.09",
    role: "웹 퍼블리싱",
    contribution: "퍼블리싱 90%",
    url: "#",
    images: ["./images/portfoilo_dari.png"],
    overview: "마케팅 통합 관리 툴 DARI의 웹사이트 퍼블리싱 작업입니다.",
    features: ["HTML5 시맨틱 마크업", "CSS3 애니메이션", "반응형 웹 디자인"],
  },
  {
    id: "loftshop",
    title: "로프트샵",
    category: "고도몰",
    thumbnail: "./images/portfoilo_loftshop.png",
    tags: ["고도몰", "HTML", "CSS", "jQuery"],
    description: "로프트샵 사이트 리뉴얼",
    client: "로프트샵",
    period: "2023.03 ~ 2023.05",
    role: "쇼핑몰 퍼블리싱",
    contribution: "퍼블리싱 100%",
    url: "https://loftshop.co.kr/",
    images: ["./images/portfoilo_loftshop.png"],
    overview:
      "로프트샵 쇼핑몰 사이트 리뉴얼 프로젝트입니다. 고도몰 플랫폼을 기반으로 커스터마이징 작업을 진행했습니다.",
    features: [
      "고도몰 템플릿 커스터마이징",
      "상품 상세 페이지 최적화",
      "모바일 최적화",
    ],
  },
  {
    id: "inus",
    title: "이누스 프렌즈몰",
    category: "카페24",
    thumbnail: "./images/portfoilo_inus.png",
    tags: ["카페24", "HTML", "CSS", "jQuery"],
    description: "이누스프렌즈몰 UX/UI 개선 작업 운영",
    client: "이누스 프렌즈몰",
    period: "2023.10 ~ 2024.02",
    role: "쇼핑몰 운영 및 개선",
    contribution: "퍼블리싱 100%, UX/UI 개선 80%",
    url: "https://ifmall.co.kr/",
    images: ["./images/portfoilo_inus.png"],
    overview: "이누스 프렌즈몰의 UX/UI 개선 및 운영 작업을 담당했습니다.",
    features: ["카페24 플랫폼 커스터마이징", "쇼핑몰 운영 및 유지보수"],
  },
];
